print("============ BOOKBOT ============")
print("Analyzing book found at books/frankenstein.txt...")
print("----------- Word Count ----------")
from stats import get_book_text,word_count, char_count, sort_on
get_book_text()
char_dict = char_count()
word_count()
print("--------- Character Count -------")
sort_on(char_dict)
print("============= END ===============")